app/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.index'))
            else:
                flash('Incorrect password, try again', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("login.html", user=current_user)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(first_name) < 2:
            flash('First name must be greater than 1 character.', category='error')
        elif len(password1) < 7:
            flash('password must be at least 7 characters.', category='error')
        elif password1 != password2:
            flash("Passwords don't match.", category='error')
        else:
            new_user = User(email=email, first_name=first_name, password=generate_password_hash(password1, method='scrypt'))
            db.session.add(new_user)
            db.session.commit()
            flash('Account created!', category='success')
            login_user(user, remember=True)
            return redirect(url_for('views.home'))

    return render_template("sign_up.html", user=current_user)

app/views.py
from app import app
from flask import Blueprint, render_template, request, redirect, url_for, flash, jsonify
from flask_login import login_required, current_user
from app.utils import get_element, selectors
from .models import Product, Opinion, Note
from . import db
from .forms import SubmitForm
import requests
import time
import json
import simplejson
import os
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import matplotlib
matplotlib.use("Agg")
from bs4 import BeautifulSoup

views = Blueprint('views', __name__)

#example of product codes 150872408,137671791,39562616,152142703

@views.route('/')
@views.route('/index')
def index():
    return render_template("index.html", user=current_user)

@views.route('/extract', methods=['GET', 'POST'])
def extract():
    form = SubmitForm()

    if request.method == 'POST':
        product_code = form.product_id.data
        if form.validate_on_submit():
            all_opinions = []
            url = f"https://www.ceneo.pl/{product_code}#tab=reviews"
            if form.validate_url(url):
                while(url):
                    response =  requests.get(url)
                    page = BeautifulSoup(response.text, 'html.parser')
                    opinions = page.select("div.js_product-review")
                    for opinion in opinions:
                        single_opinion = {}
                        for key, value in selectors.items():
                            single_opinion[key] = get_element(opinion, *value)
                        all_opinions.append(single_opinion)
                        new_opinion = Opinion(opinion_id=single_opinion["opinion_id"], author=single_opinion["author"], recommendation=single_opinion["recommendation"], score=single_opinion["score"], purchased=single_opinion["purchased"], published_at=single_opinion["published_at"], purchased_at=single_opinion["purchased_at"], thumbs_up=single_opinion["thumbs_up"], thumbs_down=single_opinion["thumbs_down"], content=single_opinion["content"], pros=','.join(single_opinion["pros"]), cons=','.join(single_opinion["cons"]), product_code=product_code)
                        db.session.add(new_opinion)
                        db.session.commit()
                    try:
                        url = f"https://www.ceneo.pl" + get_element(page, "a.pagination__next", "href")
                    except TypeError: 
                        url =  None
                if len(all_opinions) == 0:
                    flash('Brak opinii o produkcie', category='error')
                    return redirect(url_for("views.extract", form=form, product_code=product_code), user=current_user)
            else:
                flash('Błędne id produktu', category='error')
                time.sleep(0.5)
                return redirect(url_for("views.extract", form=form, product_code=product_code), user=current_user)

            #json
            try:
                os.mkdir("./app/static/opinions")
            except FileExistsError:
                pass
            with open(f"./app/static/opinions/{product_code}.json", 'w', encoding = "UTF-8") as jf:
                json.dump(all_opinions, jf, indent=4, ensure_ascii=False)   
            #csv
            with open(f"./app/static/opinions/{product_code}.csv", 'w', encoding = "UTF-8") as cf:
                dcf = pd.DataFrame(all_opinions)
                dcf.to_csv(f"./app/static/opinions/{product_code}.csv")
            #xlsx
            with open(f"./app/static/opinions/{product_code}.xlsx", 'w', encoding = "UTF-8") as xf:
                df = pd.DataFrame(all_opinions).to_excel(f"./app/static/opinions/{product_code}.xlsx")

            opinions = pd.read_json(json.dumps(all_opinions,ensure_ascii=False))
            opinions.score = opinions.score.map(lambda x: float(x.split("/")[0].replace(",",".")))
            stats = {
                "opinions_count": opinions.shape[0],
                "pros_count": int(opinions.pros.map(bool).sum()),
                "cons_count": int(opinions.pros.map(bool).sum()),
                "avg_score": opinions.score.mean().round(2)

            }

            score = opinions.score.value_counts().reindex(list(np.arange(0, 5.5, 0.5)), fill_value = 0)
            score.plot.bar(color="hotpink")
            plt.xticks(rotation=0)
            plt.title("Histogram ocen")
            plt.xlabel("Liczba gwiazdek")
            plt.ylabel("Liczba opinii")
            plt.ylim(0,max(score.values)+1.5)
            for index, value in enumerate(score):
                plt.text(index, value+0.5, str(value), ha="center")
            try:
                os.mkdir("./app/static/plots")
            except FileExistsError:
                pass
            plt.savefig(f"./app/static/plots/{product_code}_score.png")
            plt.close()

            recommendation = opinions["recommendation"].value_counts(dropna = False).reindex(["Nie polecam", "Polecam", np.nan])
            print(recommendation)
            recommendation.plot.pie(
                label="",
                autopct="%1.1f%%",
                labels= ["Nie polecam", "Polecam", "Nie mam zdania"],
                colors= ["crimson", "forestgreen", "gray"]
            )

            plt.legend(bbox_to_anchor=(1.0,1.0))
            plt.savefig(f"./app/static/plots/{product_code}_recommendation.png")
            plt.close()

            stats['score'] = score.to_dict()
            stats['recommendation'] = recommendation.to_dict()
            try:
                os.mkdir("./app/static/stats")
            except FileExistsError:
                pass
            with open(f"./app/static/stats/{product_code}.json", 'w', encoding = "UTF-8") as jsf:
                simplejson.dump(stats, jsf, indent=4, ensure_ascii=False, ignore_nan=True)

            new_product = Product(product_code=product_code, opinions_num=stats["opinions_count"], pros=stats["pros_count"], cons=stats["cons_count"], mean_score=stats["avg_score"])
            db.session.add(new_product)
            db.session.commit()

            return redirect(url_for('views.product', product_code=product_code, user=current_user ))
        
        else:
            flash('Błędne id produktu', category='error')
            time.sleep(0.5)
            return redirect(url_for("views.extract", form=form, product_code=product_code, user=current_user))
        
    return render_template("extract.html", form=form, user=current_user)

@views.route('/products', methods=['GET', 'POST'])
def products():
    products = Product.query.order_by(Product.date_created).all()
    files = os.listdir('app/static/stats')
    product_opinion_list = []
    for f in files:
        with open(f"app/static/stats/{f}", 'r', encoding='utf-8') as jsf:
            js = json.load(jsf)
        product_opinion_list.append((f.split('.')[0],js))
    return render_template("products.html",products=products, p_o_list = product_opinion_list, user=current_user)

@views.route('/author')
def author():
    return render_template("author.html", user=current_user)

@views.route('/product/<product_code>', methods=['GET', 'POST'])
def product(product_code):
    product = Product.query.filter_by(product_code=product_code).first()
    with open(f"app/static/opinions/{product_code}.json", 'r', encoding='utf-8') as jsf:
        js = json.load(jsf)
    return render_template("product.html", product_code=product_code, product=product, opinions_list=js, user=current_user)


@views.route('/notes', methods=['GET', 'POST'])
@login_required
def notes():
    if request.method == 'POST':
        note = request.form.get('note')

        if len(note) < 1:
            flash('Note is too short!', category='error')
        else:
            new_note = Note(data=note, user_id=current_user.id)
            db.session.add(new_note)
            db.session.commit()
            flash('Note added!', category='success')
            
    return render_template("home.html", user=current_user)

@views.route('/delete-note', methods=['POST'])
def delete_note():
    note = json.loads(request.data)
    noteId = note['noteId']
    note = Note.query.get(noteId)
    if note:
        if note.user_id == current_user.id:
            db.session.delete(note)
            db.session.commit()

    return jsonify({})

app/templates/author.html
{% extends "base.html" %}

{% block content %}
<div class="col-7 pt-2">
    <h3 class="text-center"> O autorze </h3>
    <p class="text-start"> 
        Name: Mikołaj Sokołowski <br>
        Email: 226572@student.uek.krakow.pl<br>
        

        Bio: Uczeń UEK informatyki stosowanej 
    </p>
</div>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/dataTables.bootstrap5.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.css" />
    <script src="https://kit.fontawesome.com/c2e5f11c19.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script defer src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script defer src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
    <script defer src="https://cdn.datatables.net/1.13.4/js/dataTables.bootstrap5.min.js"></script>
    <script defer src="{{ url_for('static', filename='script.js')}}"></script>
    
    <title>CeneoWebScraper</title>
</head>

<body class="d-flex flex-column min-vh-100 bg-gray-100 text-center text-black">
    <nav class="navbar navbar-expand-lg bg-body-tertiary bg-dark" data-bs-theme="dark">
        <div class="container-fluid">
          <a class="navbar-brand disabled" ><i class="fa-solid fa-compass"></i></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('views.notes')}}"> <i class="bi bi-person"></i> O autorze </a>
              </li>
              {% endif %}
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{url_for('views.index')}}"> <i class="bi bi-house-fill"></i> Strona główna </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('views.extract')}}"> <i class="bi bi-arrow-bar-up"></i> Ekstrakcja opinii </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('views.products')}}"> <i class="bi bi-list-stars"></i> Lista produktów </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('views.author')}}"> <i class="bi bi-person"></i> O autorze </a>
              </li>
          </div>
          </ul>
          <ul class="navbar-nav d-flex">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('auth.logout')}}"> logout </a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('auth.login')}}"> login </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('auth.sign_up')}}"> sign up </a>
            </li>
            {% endif %}
          </ul>
        </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
      {% if category == 'error' %}
      <div class="alert alert-danger" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      {% else %}
      <div class="alert alert-success" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      {% endif %}
      {% endfor %}
    {% endif %}
    {% endwith %}

    <div class="container text-center align-items-center">
        <div class="row mb-3 align-items-center justify-content-center">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    <footer class="footer mt-auto py-3 bg-dark text-center text-white">
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
            © 2023 Copyright:  Mikolaj Sokolowski, Uniwersytet Ekonomiczny w Krakowie
            <a class="btn btn-outline-light btn-floating m-1" href="https://github.com/SokolowskiMik" role="button" target=”_blank”
            ><i class="fab fa-github"></i></a>
        </div>
    </footer>
    <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>
</body>
</html>

app/templates/extract.html
{% extends "base.html" %}

{% block content %}
<div class="col-4 pt-2">
    <form id="submitForm" method="POST" action="{{url_for('views.extract')}}">
        <!-- <label for="product-id" class="form-label"> Wpisz id produktu </label> -->
        {{ form.product_id.label}}
        <div class="input-group mb-3">
            {{ form.csrf_token }}
            {{ form.product_id(class="form-control", placeholder="type in product id") }} 
            <!-- <input type="text" class="form-control" id="product_id" name="product_id" placeholder="type in product id" aria-describedby="submit-button"> -->
            <input class="btn btn-outline-secondary" id="submit-button" type="submit" value="Pobierz">
        </div>
    </form>
    {{ product_code }}
</div>
{% endblock %}

app/templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="col-7 pt-2">
    <h2 class="text-center"> Opis projektu </h2>
    <h3 class="text-start"> Cel aplikacji: </h3>
    <p class="text-start"> Celem działania aplikacji jest pobieranie opinii o produktach z serwisu Ceneo.pl. Dla 
        produktu, którego kod zostanie podany jako parametr należy pobrać jego nazwę oraz 
        wszystkie dostępne opinie o nim </p>
    <h3 class="text-start"> Opis aplikacji: </h3>
    <p class="text-start"> Aplikacja pobiera wpisany numer identyfikacyjny produktu i pobiera dla niego wszystkie dane ktore nastepnie sa umieszczane na stronie </p>
    <h3 class="text-start"> Zastosowane biblioteki: </h3>
    <ul class="list-group">
        <li class="list-group-item">Requests</li>
        <li class="list-group-item">BeautifulSoup4</li>
        <li class="list-group-item">Json</li>
        <li class="list-group-item">Os</li>
        <li class="list-group-item">Pandas</li>
        <li class="list-group-item">Flask</li>
        <li class="list-group-item">jquery</li>
        <li class="list-group-item">jinja2</li>
      </ul>
    <h3 class="text-start"> Zastosowane podejscia: </h3>
    <p class="text-start"> aplikacja zostala stworzona... </p>
</div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}


{% block content %}
<div class="col-7 pt-2">
    <h2 class="text-center"> Opis projektu </h2>
    <h3 class="text-start"> Cel aplikacji: </h3>
    <p class="text-start"> Celem działania aplikacji jest pobieranie opinii o produktach z serwisu Ceneo.pl. Dla 
        produktu, którego kod zostanie podany jako parametr należy pobrać jego nazwę oraz 
        wszystkie dostępne opinie o nim </p>
    <h3 class="text-start"> Opis aplikacji: </h3>
    <p class="text-start"> Aplikacja pobiera wpisany numer identyfikacyjny produktu i pobiera dla niego wszystkie dane ktore nastepnie sa umieszczane na stronie </p>
    <h3 class="text-start"> Zastosowane biblioteki: </h3>
    <ul class="list-group text-start">
        <li class="list-group-item">Requests</li>
        <li class="list-group-item">BeautifulSoup4</li>
        <li class="list-group-item">Json</li>
        <li class="list-group-item">Os</li>
        <li class="list-group-item">Pandas</li>
        <li class="list-group-item">Flask</li>
        <li class="list-group-item">jquery</li>
        <li class="list-group-item">jinja2</li>
      </ul>
    <h3 class="text-start"> Zastosowane podejscia: </h3>
    <p class="text-start"> aplikacja zostala stworzona przy wykorzystaniu sqlalchemy oraz podejscia obiektowego mam nadzieje :p </p>
</div>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}



{% block content %}
<div class="col-4 pt-2">
    <form method="POST">
        <h3 align="center">Login</h3>
        <div class="form-group">
            <label for="email">Email Adress</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="Enter email"/>
        </div>

        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Enter password"/>
        </div>
        
        <br>
        <button type="submit" class="btn btn-primary">Login</button>
    </form>
</div>
{% endblock %}

app/templates/notes.html
{% extends "base.html" %}

{% block content %}
<h1 align="center">Notes</h1>
<form method="POST">
    <textarea name="note" id="note" class="form-control"></textarea>
    <br />
    <div align="center">
        <button type="submit" class="btn btn-primary">Add Note</button>
    </div>
</form>

<ul class="list-group list-group-flush" id="notes">
    {% for note in user.notes %}
    <li class="list-group-item">{{ note.data }}
        <button type="button" class="close" onClick="deleteNote({{ note.id }})">
            <span aria-hidden="true">&times;</span>
        </button>
    </li>
    {% endfor %}
</ul>
{% endblock %}

app/templates/product.html
{% extends "base.html" %}


{% block content %}
<h3>{{product_code}}</h3>
<div class="container pt-5">
    
    <div class="btn-group">
        <a href="{{url_for('static', filename='./opinions/'+product_code+'.csv')}}" download="{{product_code.csv}}" class="text-decoration-none"><button type="button" class="btn btn-outline-secondary">csv
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-download" viewBox="0 0 16 16">
<path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
<path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"/>
</svg>
          <span class="visually-hidden">csv</span>
        </button></a>
        <a href="{{url_for('static', filename='./opinions/'+product_code+'.xlsx')}}" download="{{product_code.xlsx}}" class="text-decoration-none"><button type="button" class="btn btn-outline-secondary">xlsx
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-download" viewBox="0 0 16 16">
<path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
<path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"/>
</svg>
          <span class="visually-hidden">xlsx</span>
        </button></a>
        <a href="{{url_for('static', filename='./opinions/'+product_code+'.json')}}" download="{{product_code.json}}"  class="text-decoration-none"><button type="button" class="btn btn-outline-secondary">json
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-download" viewBox="0 0 16 16">
<path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
<path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"/>
</svg>
          <span class="visually-hidden">json</span>
        </button></a>
    </div>

    <!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
    Wykresy
  </button>
  
  <!-- Modal -->
  <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="staticBackdropLabel">Wykresy</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <h2 class="fs-5">Wykres kołowy</h2>
            <img 
            src="{{ url_for('static', filename='./plots/'+product_code+'_recommendation.png')}}" alt="wykres kołowy"
            />

            <h2 class="fs-5">Wykres kolumnowy</h2>
            <img 
            src="{{ url_for('static', filename='./plots/'+product_code+'_score.png')}}" alt="wykres kolumnowy"
            />
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

    <a href="{{url_for('views.products')}}"><button type="button" class="btn btn-dark"> Lista produktów </button></a>
    
    <h3 class="text-center"> Pobrane opinie: </h3>
    <table id="example" class="table table-striped pt-1" style="width:100%">
      <thead>
          <tr>
              <th>id opinii</th>
              <th>Autor</th>
              <th>rekomendacja</th>
              <th>liczba gwiazdek</th>
              <th>potwierdzenie zakupem</th>
              <th>data wystawienia opinii</th>
              <th>data zakupu produktu</th>
              <th>opinia przydatna</th>
              <th>opinia nieprzydatna</th>
              <th>treść</th>
              <th>lista wad</th>
              <th>lista zalet</th>
          </tr>
      </thead>
      <tbody>
        <!-- {% for opinion in opinions_list %}
        <tr>
              <td>{{opinion["opinion_id"]}}</td>
              <td>{{opinion["author"]}}</td>
              <td>{{opinion["recommendation"]}}</td>
              <td>{{opinion["score"]}}</td>
              <td>{{opinion["purchased"]}}</td>
              <td>{{opinion["published_at"]}}</td>
              <td>{{opinion["purchased_at"]}}</td>
              <td>{{opinion["thumbs_up"]}}</td>
              <td>{{opinion["thumbs_down"]}}</td>
              <td>{{opinion["content"]}}</td>
              <td>{{opinion["pros"]}}</td>
              <td>{{opinion["cons"]}}</td>
          </tr>
        {% endfor %} -->
        {% for opinion in product.opinions %}
        <tr>
              <td>{{opinion.opinion_id}}</td>
              <td>{{opinion.author}}</td>
              <td>{{opinion.recommendation}}</td>
              <td>{{opinion.score}}</td>
              <td>{{opinion.purchased}}</td>
              <td>{{opinion.published_at}}</td>
              <td>{{opinion.purchased_at}}</td>
              <td>{{opinion.thumbs_up}}</td>
              <td>{{opinion.thumbs_down}}</td>
              <td>{{opinion.content}}</td>
              <td>{{opinion.pros}}</td>
              <td>{{opinion.cons}}</td>
          </tr>
        {% endfor %}
        </tbody>
        <tfoot>
            <tr>
                <th>id opinii</th>
                <th>Autor</th>
                <th>rekomendacja</th>
                <th>liczba gwiazdek</th>
                <th>potwierdzenie zakupem</th>
                <th>data wystawienia opinii</th>
                <th>data zakupu produktu</th>
                <th>opinia przydatna</th>
                <th>opinia nieprzydatna</th>
                <th>treść</th>
                <th>lista wad</th>
                <th>lista zalet</th>
            </tr>
      </tfoot>
  </table>

</div>
{% endblock %}

<script>
    const myModal = document.getElementById('myModal')
    const myInput = document.getElementById('myInput')

    myModal.addEventListener('shown.bs.modal', () => {
    myInput.focus()
    })
</script>

app/templates/sign_up.html
{% extends "base.html" %}


{% block content %}
<div class="col-4 pt-2">
    <form method="POST">
        <h3 align="center">Sign Up</h3>
        <div class="form-group">
            <label for="email">Email Adress</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="Enter email"/>
        </div>
        <div class="form-group">
            <label for="firstName">name</label>
            <input type="text" class="form-control" id="firstName" name="firstName" placeholder="Enter first name"/>
        </div>
        <div class="form-group">
            <label for="password1">Password</label>
            <input type="password" class="form-control" id="password1" name="password1" placeholder="Enter password"/>
        </div>
        <div class="form-group">
            <label for="password2">Password (Confirm)</label>
            <input type="password" class="form-control" id="password2" name="password2" placeholder="Confirm password"/>
        </div>
        <br>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}